config/routes.rb
Rails.application.routes.draw do
  root 'talks#index'

  resources :talks, only: [:index] do
    resources :reservations, only: [:new, :create] do
      member do
        get 'confirm/:token' => 'reservations#confirm', as: :confirm
        get 'ticket' => 'reservations#ticket', as: :ticket
      end
    end
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :talk
  validates :title, presence: true
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true
  validates :telephone, presence: true
  validates :token, uniqueness: true
  validates :status, presence: true
  before_create :generate_token

  STATUS_NOT_CONFIRMED = 0
  STATUS_CONFIRMED = 1

  private
  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  has_many :reservations
  validates :name, presence: true
  validates :description, presence: true
  validates :max_reservations, presence: true
  validates :count, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @talk = Talk.find_by(id: params[:talk_id])
    @talk.update(count: @talk.count + 1)
    @reservation = Reservation.new
    if @talk.reservations.count >= @talk.max_reservations
      flash[:danger] = 'ขออภัย ที่นั่งในช่วงนี้เต็มแล้ว'
      redirect_to root_path
    end
  end

  def create
    @talk = Talk.find_by(id: params[:talk_id])
    @talk.update(count: @talk.count + 1)
    if @talk.reservations.count >= @talk.max_reservations
      flash[:danger] = 'ขออภัย ที่นั่งในช่วงนี้เต็มแล้ว'
      redirect_to root_path
    else
      if Reservation.where(email: reservation_params[:email], talk: @talk).any?
        flash[:danger] = 'ขออภัย คุณได้ทำการลงทะเบียนแล้ว'
        redirect_to root_path
      else
        @reservation = @talk.reservations.new(reservation_params)
        @reservation.status = Reservation::STATUS_NOT_CONFIRMED
        if @reservation.valid?
          @reservation.save
          flash[:success] = 'ลงทะเบียนเรียบน้อย ระบบได้ทำการส่งอีเมลไปหาท่าน เพื่อให้ท่านยืนยันการเข้าร่วมงาน หากไม่ยืนยันภายใน 24 ชั่วโมง การสำรองที่นั่งนี้จะถูกยกเลิก'
          Resque.enqueue(MailingJob, @reservation.id)
          redirect_to root_path
        else
          render 'new'
        end
      end
    end
  end

  def confirm
    reservation = Reservation.find_by(token: params[:token])
    reservation.update(status: Reservation::STATUS_CONFIRMED)
    Resque.enqueue(MailingJob, reservation.id)
    flash[:success] = 'ยืนยันการเข้าร่วมงานเรียบร้อย ระบบได้ส่งบัตรเข้าร่วมการฟังเสวนาให้ท่านทางอีเมลเรียบร้อยแล้ว'
    redirect_to root_path
  end

  def ticket
    @reservation = Reservation.find_by(id: params[:id])
  end

  private
  def reservation_params
    params.require(:reservation).permit(:title, :fname, :lname, :telephone, :email)
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def html_renderer
    options = {filter_html: true}
    renderer = Redcarpet::Render::HTML.new(options)
  end

  def markdown(text)
    Redcarpet::Markdown.new(html_renderer).render(text).html_safe
  end

  def bootstrap_class_for flash_type
    case flash_type
    when 'success'
      'alert-success' # Green
    when 'danger'
      'alert-danger' # Red
    when 'warning'
      'alert-warning' # Yellow
    when 'info'
      'alert-info' # Blue
    else
      flash_type.class.to_s
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t 'page_title' %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to t('page_title'), root_path, class: 'navbar-brand' %>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= render partial: 'layouts/flash', flash: flash %> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/reservations/_errors.html.erb
<% if @reservation.errors.any? %>
  <div class="alert alert-danger">
    มีข้อผิดพลาด <%= @reservation.errors.count %> จุด ดังต่อไปนี้
    <ul>
      <% @reservation.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/reservations/new.html.erb
<div class="text-center h3">ลงทะเบียนเข้าฟัง<br/><%= @talk.name %></div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'errors' %>
    <%= form_for([@talk, @reservation], html: {class: 'form-horizontal'}) do |f| %>
      <div class="form-group">
        <%= f.label :title, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :fname, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :fname, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :lname, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :lname, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :telephone, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.text_field :telephone, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class: 'col-md-3 control-label' %>
        <div class="col-md-9">
          <%= f.email_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary form-control' %>
      </div>
    <% end %>
  </div>
</div>

app/views/talks/_talk.html.erb
<h4><%= talk.name %></h4>
<div>วันที่ <%= l talk.start_at, format: :formal %></div>
<div>เวลา <%= l talk.start_at, format: :time_only %> - <%= l talk.end_at, format: :time_only %></div>
<div><%= markdown(talk.description) %></div>
<%= link_to 'ลงทะเบียนเข้าร่วมงาน', new_talk_reservation_path(talk), class: 'btn btn-primary' %>

app/views/talks/index.html.erb
<div class="text-center h3">77 ปี ต.อ. เสวนาวิชาการ</div>
<div class="text-center h5">26-27 ธันวาคม 2557</div>
<div class="text-center h5">ณ ห้อง 111 ตึก 2 โรงเรียนเตรียมอุดมศึกษา</div>
<% Talk.all.each do |t| %>
  <%= render partial: 'talk', object: t %>
<% end %>